=== iAmNikola/xml-project/data/z_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.foolstech.com/z1" xmlns:z1="http://www.foolstech.com/z1">

    <xs:element name="Zahtev_za_priznanje_ziga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Podnosilac_prijave" type="z1:TLice"/>
                <xs:element minOccurs="0" name="Punomocnik" type="z1:TLice"/>
                <xs:element minOccurs="0" name="Zajednicki_predstavnik" type="z1:TLice"/>
                <xs:element name="Podaci_o_znaku">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Tip_ziga" type="z1:TTip_ziga"/>
                            <xs:element name="Tip_znaka" type="z1:TTip_znaka"/>
                            <xs:element name="Izgled_znaka" type="z1:TDokument"/>
                            <xs:element name="Naznacenje_boje">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element minOccurs="0" name="Transliteracija_znaka">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element minOccurs="0" name="Prevod_znaka">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Opis_znaka" minOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Zatrazeno_pravo_prvenstva_i_osnov">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Klase">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="45" minOccurs="1" name="Klasa">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                  <xs:minInclusive value="1"/>
                                                  <xs:maxInclusive value="45"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_placanju">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Osnovna_taksa" type="xs:int"/>
                            <xs:element name="Taksa_za_klase">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:int">
                                            <xs:attribute name="broj_klasa">
                                                <xs:simpleType>
                                                  <xs:restriction base="xs:int">
                                                  <xs:minExclusive value="1"/>
                                                  <xs:maxExclusive value="45"/>
                                                  </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Taksa_za_graficko_resenje" type="xs:int"/>
                            <xs:element name="Ukupno" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_zavodu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Primerak_znaka" type="z1:TDokument"/>
                            <xs:element maxOccurs="1" name="Spisak_robe_i_usluge">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="45" name="Roba_i_usluge"
                                            type="z1:TRoba_i_usluge"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Punomocje" type="z1:TDokument"/>
                            <xs:element name="Generalno_punomocije_ranije_prilozeno"
                                type="xs:boolean"/>
                            <xs:element name="Punomocje_ce_biti_naknadno_dostavljeno"
                                type="xs:boolean"/>
                            <xs:element name="Opsti_akt" type="z1:TDokument"/>
                            <xs:element name="Dokaz_o_pravu_prvenstva" type="z1:TDokument"/>
                            <xs:element name="Dokaz_o_uplati_takse" type="z1:TDokument"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="institucija" form="unqualified" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="broj_prijave" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="(Z-)[0-9]{4}/[0-9]{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="datum_podnosenja" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Adresa">
        <xs:complexType>
            <xs:all>
                <xs:element name="Ulica">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Postanski_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]{5,6}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Mesto">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Drzava">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="Kontakt">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Telefon">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="12"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Email">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern
                                value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"/>
                            <xs:minLength value="1"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Faks">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" block="" name="TLice">
        <xs:sequence>
            <xs:element ref="z1:Adresa"/>
            <xs:element ref="z1:Kontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="z1:TLice">
                <xs:sequence>
                    <xs:element name="Ime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="100"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="Prezime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="100"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="z1:TLice">
                <xs:sequence>
                    <xs:element name="Poslovno_ime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="100"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TTip_ziga">
        <xs:attribute name="tip" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="(individualni_zig|kolektivni_zig|zig_garancije)"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="TTip_znaka">
        <xs:attribute name="tip" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern
                        value="(verbalni_znak|graficki_znak|kombinovani_znak|trodimenzionalni_znak|druga_vrsta_znaka)"
                    />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="TDokument">
        <xs:attribute name="putanja" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                    <xs:maxLength value="100"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="TRoba_i_usluge">
        <xs:sequence>
            <xs:element maxOccurs="100" name="Usluga">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="klasa">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="1"/>
                    <xs:maxInclusive value="45"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== iAmNikola/xml-project/data/z_input.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_priznanje_ziga xmlns="http://www.foolstech.com/z1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.foolstech.com/z1 file:/Users/vladanmikic/Documents/fakultet/semestar7/xml/xml-project/schemas/z_schema.xsd"
    institucija="Neka ad"
    broj_prijave="Z-1231/12"
    datum_podnosenja="2022-11-11">
    <Podnosilac_prijave xsi:type="TFizicko_lice">
        <Adresa>
            <Ulica>Sumska 1</Ulica>
            <Postanski_broj>32123</Postanski_broj>
            <Mesto>Novi Sad</Mesto>
            <Drzava>Srbija</Drzava>
        </Adresa>
        <Kontakt>
            <Telefon>+12312312</Telefon>
            <Email>nesto@gmail.com</Email>
            <Faks>Neki faks</Faks>
        </Kontakt>
        <Ime>Neko</Ime>
        <Prezime>Nekic</Prezime>
    </Podnosilac_prijave>
    <Podaci_o_znaku>
        <Tip_ziga tip="individualni_zig"/>
        <Tip_znaka tip="verbalni_znak"/>
        <Izgled_znaka putanja="usr/docs/dokument"/>
        <Naznacenje_boje>plava, zuta, zelena</Naznacenje_boje>
        <Opis_znaka>Neki opis</Opis_znaka>
        <Zatrazeno_pravo_prvenstva_i_osnov>Nesstooooo</Zatrazeno_pravo_prvenstva_i_osnov>
        <Klase>
            <Klasa>2</Klasa>
            <Klasa>3</Klasa>
        </Klase>
    </Podaci_o_znaku>
    <Podaci_o_placanju>
        <Osnovna_taksa>112</Osnovna_taksa>
        <Taksa_za_klase>1212</Taksa_za_klase>
        <Taksa_za_graficko_resenje>1212</Taksa_za_graficko_resenje>
        <Ukupno>12121</Ukupno>
    </Podaci_o_placanju>
    <Podaci_o_zavodu>
        <Primerak_znaka putanja="usr/docs/dokument"/>
        <Spisak_robe_i_usluge>
            <Roba_i_usluge klasa="1">
                <Usluga>nesto</Usluga>
                <Usluga>nesto drugo, nesto jos, nesto</Usluga>
            </Roba_i_usluge>
        </Spisak_robe_i_usluge>
        <Punomocje putanja="nesto"/>
        <Generalno_punomocije_ranije_prilozeno>false</Generalno_punomocije_ranije_prilozeno>
        <Punomocje_ce_biti_naknadno_dostavljeno>true</Punomocje_ce_biti_naknadno_dostavljeno>
        <Opsti_akt putanja="neka/nesto"/>
        <Dokaz_o_pravu_prvenstva putanja="neka/nesto"/>
        <Dokaz_o_uplati_takse putanja="neka/nesto"/>
    </Podaci_o_zavodu>
</Zahtev_za_priznanje_ziga>
